# Use an official Node.js runtime as the base image
FROM node:18

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json (or yarn.lock) to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Build the Vite application for production
RUN npm run build

# Install serve to serve the static files
RUN npm install -g serve

# Use serve to serve the app
CMD ["serve", "-s", "dist", "-l","80"]

# Expose the port the app runs on
EXPOSE 80