services:

  express:
    build: ./server/
    image: express:latest
    ports:
      - "4000:4000"
    environment:
     - MONGODB_URL=${MONGODB_URL}
     - SECRET=${SECRET}
     - API_KEY=${API_KEY}

  react:
    build: ./client/
    image: react:latest
    ports:
      - "80:80"
